benawad/destiny

README.md
I've just added two badges to the readme:
- The first one, links to the package on npm and shows its version.
- And the other is just showing that contibutions are welcome.
[See the change.](https://github.com/AnatoleLucet/butler-cli/blob/doc/badges/README.md)
=> Adding npm version et contibuting badges to the readme

.eslintrc.js, package.json, src/index/buildGraph/findEdges.ts, src/index/toFractalTree.ts, yarn.lock
This PR is adding a script named `lint` which should regulate a bit the code base.
I think adding something like the following in the PR template could also help:
"Don't forget to run `yarn lint` before submitting your new pull request."
=> Adding a linting script

.eslintrc.js, package.json, src/index/toFractalTree.ts, yarn.lock
Prettier and ESLint were in conflict.
This should be fixed with this PR.
=> Implementing Prettier to ESLint config

tests/build-graph.test.ts, tests/end-to-end.test.ts, tests/to-fractal-tree.test.ts
Imports were messed up in tests
=> fixing imports in tests

package.json, src/index.ts, yarn.lock
I have added Commander to the project. This is going to be useful for more complex integrations on the cli.
I have also changed the bin from `butler-cli` to `butler`. https://github.com/benawad/butler-cli/issues/3#issue-565432552
=> Switching to Commander for the cli, and renaming bin to 'butler'

README.md
A little disclaimer until 1.0.
=> Adding disclaimer in readme

.github/workflows/CI.yml
Just made a basic CI workflow #25 using github action.
=> CI workflow

src/index.ts, src/index/formatFileStructure.ts
This PR is an attempt to increase the readability of our main module and `formatFileStructure`. It's opinionated so feel free shoot it down if it doesn't fit your taste.
=> refactor: improve readability of main and formatFileStructure

src/index.ts, src/index/formatFileStructure.ts, src/index/formatFileStructure/toFractalTree.ts, src/shared/logger.ts
I've created this `logger.ts` utility to normalize logs.
I've also added logs at specific steps in the engine so the user get more infos about what's going on.
(yes it looks like Bazel's logs).
This can probably be improved. But for now, it's getting the job done.
=> Creating a logger utility

src/index/formatFileStructure/shared/findEdges.ts, tests/__snapshots__/end-to-end.test.ts.snap, tests/build-graph.test.ts, tests/fixtures/commented-imports/index.js, tests/to-fractal-tree.test.ts
fixes https://github.com/benawad/destiny/issues/42
=> findEdges: remove comments before searching for imports

src/index/formatFileStructure/toFractalTree.ts
Improve readability and make more DRY
=> fix(toFractalTree): improve readability and make more DRY

src/index/formatFileStructure.ts
=> removes duplicate unused files from logger.warn

src/index/formatFileStructure.ts, src/index/formatFileStructure/removeEmptyFolders.ts
I've been trying to understand how destiny works and am having trouble reading and understanding the code.
Some of it is self explanatory like this function, but other parts like `addEdge()` (What is an 'edge'? I still don't understand) and `buildFractal()`.
The nesting of `if` statements is hard to interpret, so I cleaned those up too.
Is this kind of pull request ok? It helps the new and next person, which may well be you. I'd be happy to go through destiny and do this.
=> enhances code readability and adds TSDoc to "removeEmptyFolders"

package.json, src/index.ts, src/index/getFilePaths.ts, tests/to-fractal-tree.test.ts, tsconfig.json
- added a typescript check.
- fixed some typescript warnings.
=> Some improvements

src/index/formatFileStructure/fixImports.ts, src/index/generateTrees/buildGraph.ts, src/index/shared/customResolve.ts, tests/__snapshots__/end-to-end.test.ts.snap, tests/fixtures/cra/App.js
=> fix: don't fail if can't find file

src/index.ts
This adds support to specify paths in your config via the `include` key. The paths should be listed in a array.
=> fix: support paths in config via include

README.md
I've simply moved the "side by side" image to the top of the readme.
See:
https://github.com/benawad/destiny/blob/doc/rearranging-readme/README.md
I've made this PR just to make sure everyone is ok with this tiny change.
=> Rearranging the readme

src/index/formatFileStructure/moveFiles.ts
A quick format of 1 file from files I had reworked from a previously closed pull.
=> code cleanup on aisle "moveFiles"

README.md
I've just made some kind of a base for the doc. You can see it here: 
https://github.com/benawad/destiny/wiki
I really hope for some suggestions. This probably needs to be improved, but I guess I have done the boring work by making this "base". 😄
=> Documentation base

README.md
Add preview of the options available in the readme.
=> docs: add --help string

src/index.ts, src/index/printHelpMessage.ts, tests/print-help-message.test.ts
This is better than manually adding spaces to indent the flags and descriptions in the help message.
> Note: I'm going to add tests for this PR in the week.
=> creating a printHelpMessage function

src/index/formatFileStructure/fixImports.ts, src/index/generateTrees/buildGraph.ts
Without logging the directory, it is difficult to know what to fix, especially with large codebases.
=> Add dirs to logging

tests/logger.test.ts
This is in relation to #80 
I'm adding two tests to complete line coverage and test the function writeDebugStdout() in `logger.ts`. The coverage now for the file is 100%!
=> Adding new tests for logger.writeDebugStdout()
